name: build-HIGH

on:
  
  push:
    branches: 
      - 'failed'
    tags:
      - 'v[0-9].[0-9]'

jobs:
  build:
    if:  ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
      # 2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'

        
      # 3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        continue-on-error: true
        env:
          SLACK_CHANNEL: submission
          SLACK_COLOR: '#ff00ff' # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: Scan failed - Zou Yi Song
          SLACK_USERNAME: DipSA 57 CICD
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_TEST }}

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.WEBOOKTESTTOKEN }}
          channel_id: ${{ secrets.CHANNEL_TEST_ID }}
          file_path: 'trivy-results.txt'
          initial_comment: 'post by ZOU YISONG'

   
     
