name: build

on:
  
  push:
    branches: 
      - 'failed'
    tags:
      - 'v[0-9].[0-9]'
  pull_request:
    branches: [ "failed" ]

jobs:
  build:
    #if: ${{ !startwith(commit,#NORUN)}}
    runs-on: ubuntu-latest
    steps:
      # 2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'HIGH.table'
          severity: 'HIGH'

        
      # 3
      - name: Slack failed Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: devops
          SLACK_COLOR: '#ff00ff' # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: Scan failed - ZOU YISONG
          SLACK_USERNAME: CICD
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: 'xoxb-5828957891927-5846920816146-MAMo5SZfdkgSEyjaONh4cVh9'
          channel_id: 'C05RH893PH6'
          content: 'file content'
          file_type: 'txt'
          file_name: 'trivy-result.txt'
          title: 'title of file'
          initial_comment: 'post by ZOU YISONG'

   
     
