name: build_failed

on:
  
  push:
    branches: 
      - 'failed'
    tags:
      - 'v[0-9].[0-9]'
  pull_request:
    branches: [ "failed" ] 

jobs:
  build:
    if: startsWith(${{ github.event.inputs.from-branch}},'#NOURUN') != true
    runs-on: ubuntu-latest
    steps:
      
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'HIGH.table'
          severity: 'HIGH'

        
      
      # 3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: submission
          SLACK_COLOR: 'red' # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: Scan failed - ZOY YISONG
          SLACK_USERNAME: DipSA 57 CICD
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_SUBMIT }}

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{secrets.WEBOOKTESTTOKEN}}
          channel_id: ${{secrets.CHANNEL_TEST_ID}}
          content: 'file content'
          file_type: 'txt'
          file_name: 'trivy-result.txt'
          title: 'title of file'
          initial_comment: 'post by ZOU YISONG'

   
     
